src/DjangoDemoProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/LibraryApp/urls.py
from django.urls import path
from LibraryApp import views

app_name = 'library'

urlpatterns = [
    path('', views.author_list, name='author_list'),
    path('profile/<pk>', views.user_profile, name='user_profile'),
    path('author/<pk>', views.author, name='author'),
    path('book/<pk>', views.book, name='book'),
]

src/LibraryApp/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField("book's title", max_length=100)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

class Author(models.Model):
    first_name = models.CharField("author's first name", max_length=50)
    last_name = models.CharField("author's last name",max_length=50)
    
    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

src/LibraryApp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from .models import Author, Book


def author_list(request):
    a = Author.objects.all()
    return render(request, 'author_list.html', {
        'author_list': a,
        })

def author(request, pk):
    a = get_object_or_404(Author, pk=pk)
    book_list = Book.objects.filter(author=a)
    return render(request, 'author.html', {
        'author': a,
        'book_list': book_list
        })
    
def book(request, pk):
    b = get_object_or_404(Book, pk=pk)
    return render(request, 'book.html', {
        'book': b
        })
    
def user_profile(request, pk):
    userModel = get_user_model()
    u = get_object_or_404(userModel, id=pk)
    return render(request, 'profile.html', {
        'user': u,
        })
    

src/LibraryApp/templates/author.html
<h1>{{ author.first_name }} {{ author.last_name }}</h1>
<hr/>
<h3>Libros</h3>
<ul>
{% for book in book_list %}
	<li><a href="{% url 'library:book' pk=book.pk %}">{{ book.title }}</a></li>
{% endfor %}
</ul>

src/LibraryApp/templates/author_list.html
<h3>Autores:</h3>
<ul>
{% for author in author_list%}
	<li><a href="{% url 'library:author' pk=author.pk%}">{{ author.first_name }} {{ author.last_name }}</a></li>
{% endfor %}
</ul>

src/LibraryApp/templates/book.html
<h1>{{ book.title }}</h1>
<hr/>
<h4>Autor: <a href="{% url 'library:author' pk=book.author.pk %}">{{ book.author }}</a></h4>

src/LibraryApp/templates/profile.html
<h1>
{{ user.username }} 
{% if user.first_name %}
	({{ user.first_name }} {{ user.last_name }})
{% endif %}
</h1>
<hr/>
<h4>Correo: {{ user.email }}</h4>